### ISSUE TITLE
Agent crashes during execution when trying to run JRE 17 with game version 0.96a

### ISSUE THREAD

**Issue by SteelSirokos** [necauqua/starsector-fixes#6]
For reasons I have tried and failed to discern, the java agent crashes during execution when the Starsector launcher is run from an installation of game version 0.96a RC10. The exact same setup works fine on my 0.95a installation, and Alex had no idea what if anything in the launcher code could have been changed to cause this issue on 0.96a when I asked him on the forums. As far as I can tell, the launcher seems identical to 0.95a, but I haven't and am not sure how to do any deeper testing.

![Screenshot_3](https://github.com/necauqua/starsector-fixes/assets/117305541/e41cc8a5-3956-4848-bbfd-f8834c46ea0f)

**Comment by necauqua** [comment]
huh, my guess is that since they reobfuscated the game during the new release this field got a new random-ish name, and the name the agent (which is very dumb btw) is looking for no longer exists

the thing is that iirc I don't even really need to look at the field, it was some useless thing I added for lols - like instead of trying to call the method that does not exists on jdk17 it does `logger.log("tried to do the thing")` and logger got renamed to `float` previously and now it's different 🤷

so I can just remove that and it should work again


Also they can remove that call themselves, rendering this agent completely obsolete, that call _seems_ useless (and it only even exists on old java), although I'm not sure, and running the game with the agent for a while seems to work

**Comment by SteelSirokos** [comment]
> 

Yeah, deleting the entire bytebuffer logger code block fixed it. Thanks!

**Comment by necauqua** [comment]
Cool! I'd accept a PR if it's just that.



> rendering this agent completely obsolete

Completely forgot I also use the agent to add jaxb libs and the shim thing, lol
But that can be done without an agent (and again they can easily fix this too)

**Comment by Crazy-KSK** [comment]
Could you elaborate on which lines of code to delete exactly?
thanks.

**Comment by necauqua** [comment]
Fixed in 3626f99, get it from [releases](https://github.com/necauqua/starsector-fixes/releases/tag/v1.1.0)
